### ISSUE TITLE
NSString ownership issue

### ISSUE THREAD

**Issue by myster-t** [mturner1721/MTAnimatedLabel#1]
In MTAnimatedLabel/MTAnimatedLabel.m line 132 (method -(UIFont *)font) does that toll-free bridge need to be cast as __bridge_transfer so ARC can manage the font name string you're copying from ctFont?  It seems like this might run into a potential leak with that CoreFoundation string object never getting CFReleased.

BTW, thanks for this lib!!

**Comment by myster-t** [comment]
@mturner1721 any chance you can update your library?

Thanks!

**Comment by mturner1721** [comment]
It looks like you're right, let me take a look tonight & I'll make the necessary changes. Thanks!

**Comment by myster-t** [comment]
Awesome man!  Thanks!
